### ISSUE TITLE
How I can open this project in Eclipse(Using Roku Plugin) to debug line by line?

### ISSUE THREAD

**Issue by krishnakumar-mob-incedo** [willowtreeapps/ukor#38]
How I can open this project in Eclipse(Using Roku Plugin) to debug line by line?

**Comment by nishtahir** [comment]
Ukor does not offer debugging capabilities. It's only concerned about helping you manage your project. You will still have to use `telnet` for that any form of debug functionality. See https://sdkdocs.roku.com/display/sdkdoc/Debugging+Your+Application for details.

**Comment by krishnakumar-mob-incedo** [comment]
Ok. But the project structure we have created using ukor is not supported in eclipse, trying to open but that display so many errors.

**Comment by nishtahir** [comment]
We don't officially support the project in eclipse. Our recommended editor is our [atom client](https://github.com/willowtreeapps/atom-ide-brightscript)

**Comment by krishnakumar-mob-incedo** [comment]
ok thanks.
So, atom client support debug functionality for Roku project?
And is it available for windows10 platform?/

**Comment by krishnakumar-mob-incedo** [comment]
ok thanks.

Is ukor ok for a beginner developer, who is learning Roku development?

Or  he need to first get complete knowledge using Eclipse and Roku plugin and later on start using ukor.
