### ISSUE TITLE
Need help to install my app on Roku.

### ISSUE THREAD

**Issue by krishnakumar-mob-incedo** [willowtreeapps/ukor#42]
ukor install snagfilms **.**.***.*** --auth=---------:------

I have provide ip address and auth properly while running above command.

Getting this as response and app is not showing on roku as installed app.

warn: failed to read ./ukor.local
info: make flavor: snagfilms
warn: Skipping Wist: No Wist configuration found.

**Comment by krishnakumar-mob-incedo** [comment]
I didn't get this.
Can you please where I have to check this?

By the way, I am able to create new project and also able to make new flavour of my existing project using make command.
But not able to install that.

**Comment by krishnakumar-mob-incedo** [comment]
I am tried on Roku-3 and Roku-2 both.

I will do manual installation and after that will update you.

**Comment by krishnakumar-mob-incedo** [comment]
could you try manually installing the .zip in the build directory?
Please confirm this above line of your comment.

I have to install my app .zip on Roku manually, as We do in traditional way for installing .zip on roku in debug mode.

**Comment by nishtahir** [comment]
I feel like this discussion is best had on the [Roku Developers Slack](https://join.slack.com/t/rokudevelopers/shared_invite/enQtMzU5Njc5ODM5MzAyLWE2MTIxMWQ5Nzg0Y2E3ODgzYTk4NmQxMDg2YjRjYjdiMzM5ZDU4ZTc0YmM1ZmU0Mzc5MzI3ODU3MmUxOTdlNTE)

**Comment by krishnakumar-mob-incedo** [comment]
Ya sure
